name: Autotester

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build environment and test
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Add exec flag to Jest
        run: chmod +x ./node_modules/.bin/jest

      - name: Run tests with coverage
        run: npm test

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test results
          path: coverage/lcov-report/index.html
