name: Autotester

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build environment for testing
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test

      - name: Upload Artifact with code coverage
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: coverage/lcov-report/index.html

